"""empty message

Revision ID: 022a760e2242
Revises: 5a55e18eceb5
Create Date: 2025-11-08 19:29:37.290755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022a760e2242'
down_revision = '5a55e18eceb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
