"""empty message

Revision ID: 5a55e18eceb5
Revises: 6c6d5c31a85b
Create Date: 2025-11-08 07:39:22.079088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a55e18eceb5'
down_revision = '6c6d5c31a85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('vendor_contact_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_contact_info', mysql.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
