"""empty message

Revision ID: 6c6d5c31a85b
Revises: f502218ea765
Create Date: 2025-11-08 06:06:18.249242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c6d5c31a85b'
down_revision = 'f502218ea765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_password', sa.String(length=20), nullable=False))
        batch_op.drop_column('vendor_passowrd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_passowrd', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('vendor_password')

    # ### end Alembic commands ###
