"""empty message

Revision ID: f502218ea765
Revises: 
Create Date: 2025-11-08 06:04:19.565973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f502218ea765'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_name', sa.String(length=140), nullable=False))
        batch_op.add_column(sa.Column('vendor_email', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('vendor_contact_info', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('vendor_passowrd', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('date_registered', sa.DateTime(), nullable=True))
        batch_op.drop_column('contact_info')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=140), nullable=False))
        batch_op.add_column(sa.Column('contact_info', mysql.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('date_registered')
        batch_op.drop_column('vendor_passowrd')
        batch_op.drop_column('vendor_contact_info')
        batch_op.drop_column('vendor_email')
        batch_op.drop_column('vendor_name')

    # ### end Alembic commands ###
